export const LEGAL_PAGES = {
  statut: {
    title: 'Statut editorial și independență',
    intro: 'Cine administrează publicația, cine asigură tehnologia și care sunt regulile editoriale ale proiectului.',
    sections: [
      ['Inițiativă civică personală', '„Vocea Locală Lenauheim” este o inițiativă civică și editorială independentă a persoanei fizice Droc Cristian Dan. Publicația nu este organ oficial al Primăriei Comunei Lenauheim, al Consiliului Local, al unui partid politic sau al altei autorități și nu este afiliată acestora. Denumirile instituțiilor publice sunt folosite exclusiv pentru identificare și informare.'],
      ['Responsabilitate editorială', 'Droc Cristian Dan stabilește și își asumă conținutul publicat pe site-ul principal. Opiniile sunt marcate și separate de afirmațiile factuale. Pentru informațiile de interes public sunt urmărite verificarea documentelor, indicarea surselor, actualizarea erorilor și prezentarea punctelor de vedere relevante.'],
      ['Administrare independentă', 'Site-ul principal și materialele sale sunt administrate și asumate editorial de persoana fizică Droc Cristian Dan.'],
      ['Fără finanțare publică', 'Site-ul principal nu este finanțat, comandat sau administrat de Primăria Comunei Lenauheim ori de Consiliul Local Lenauheim. Orice material electoral sau publicitate politică, dacă va exista, va fi separat și marcat potrivit legii, cu indicarea beneficiarului și a finanțării.'],
      ['Drept la replică și corectare', 'Persoanele vizate pot solicita gratuit publicarea unui punct de vedere, corectarea unei erori factuale ori eliminarea unor date publicate nelegal, folosind datele de contact afișate. Solicitarea va fi analizată într-un termen rezonabil, fără ca această procedură să limiteze dreptul de a sesiza autoritățile sau instanțele competente.'],
      ['Cadru juridic', 'Activitatea editorială se întemeiază pe libertatea de exprimare și dreptul la informație prevăzute de art. 30 și 31 din Constituția României și de art. 10 din Convenția europeană a drepturilor omului, precum și pe accesul la informații de interes public reglementat de Legea nr. 544/2001. Aceste drepturi se exercită cu respectarea demnității, reputației, vieții private, imaginii, protecției datelor, drepturilor de autor și prezumției de nevinovăție.'],
    ],
  },
  termeni: {
    title: 'Termeni de utilizare',
    intro: 'Regulile serviciului tehnic prin care candidații își administrează propriile publicații.',
    sections: [
      ['Rolurile editoriale', 'Pentru site-ul principal, inițiatorul și responsabilul editorial este persoana fizică Droc Cristian Dan. Pentru publicațiile candidaților, fiecare candidat decide conținutul, îl publică și poartă responsabilitatea editorială pentru acesta.'],
      ['Conținutul candidatului', 'Candidatul garantează că informațiile, imaginile, mărcile și celelalte materiale pot fi folosite legal și respectă legislația electorală, drepturile persoanelor, drepturile de autor și protecția datelor.'],
      ['Transparență', 'Finanțatorul real, responsabilul editorial, scrutinul, codul mandatarului financiar și informațiile contractuale trebuie menținute corecte. Platforma poate bloca publicarea când datele obligatorii lipsesc.'],
      ['Intervenția platformei', 'Conținutul aparent ilegal, reclamat sau vizat de o solicitare a autorităților poate fi suspendat ori eliminat. Contractul nu limitează obligațiile legale proprii ale operatorului platformei.'],
      ['Serviciu plătit sau gratuit', 'Forma comercială este consemnată în contract. Un serviciu oferit gratuit nu poate fi prezentat ca fiind finanțat de candidat și trebuie validat de candidat sau mandatar din perspectiva regulilor de finanțare electorală.'],
      ['Independență instituțională', 'Publicația nu este site oficial și nu este afiliată Primăriei Comunei Lenauheim, Consiliului Local Lenauheim ori unui partid politic. Nicio autoritate menționată în materiale nu răspunde pentru administrarea sau conținutul acestei publicații independente.'],
    ],
  },
  continut: {
    title: 'Politica de conținut',
    intro: 'Libertatea editorială se exercită în limitele legii și ale regulilor de siguranță ale platformei.',
    sections: [
      ['Conținut interzis', 'Nu sunt permise amenințările, hărțuirea, discriminarea, defăimarea, identitatea falsă, publicarea nelegală de date personale, încălcarea drepturilor de autor sau instrucțiunile pentru activități ilegale.'],
      ['Dovezi și surse', 'Autorul trebuie să poată susține afirmațiile factuale și să indice sursa imaginilor. Opiniile trebuie prezentate ca opinii, nu ca fapte demonstrate.'],
      ['Interes public și echilibru', 'Critica instituțiilor și a persoanelor care exercită funcții publice trebuie să privească subiecte de interes public și să se bazeze pe o documentare rezonabilă. Acuzațiile nedovedite nu vor fi prezentate drept fapte certe, iar persoanei vizate i se va oferi posibilitatea unui punct de vedere sau a dreptului la replică.'],
      ['Moderare', 'Platforma nu aprobă în prealabil fiecare afirmație, dar poate suspenda conținutul după o sesizare, când există indicii de nelegalitate ori când regulile contractuale sunt încălcate.'],
      ['Fără susținere politică', 'Furnizarea tehnologiei nu reprezintă susținerea candidatului și nu transformă operatorul platformei în autorul mesajului.'],
    ],
  },
  confidentialitate: {
    title: 'Politica de confidențialitate',
    updated: '10 septembrie 2026',
    intro: 'Această politică explică ce date personale sunt prelucrate prin Vocea Locală Lenauheim, de ce sunt necesare, cât timp sunt păstrate și ce drepturi ai.',
    sections: [
      ['Cine răspunde de date', 'Pentru site-ul principal și formularele civice, responsabil este Droc Cristian Dan. Pentru publicația unui candidat, candidatul indicat în pagina de transparență decide asupra conținutului și a datelor publicate, iar platforma asigură funcționarea tehnică. Rolurile concrete se stabilesc în funcție de operațiunea efectuată.'],
      ['Datele pe care le colectăm', 'Putem prelucra date de cont și autentificare, date de profil și contact, conținut publicat, acceptări și evidențe contractuale, jurnale de securitate, comentarii, răspunsuri la sondaje și reacții, sesizări privind conținutul și raportări de costuri. Nu solicităm prin formularul de costuri copii ale facturilor.'],
      ['Ce devine public', 'Datele de profil și materialele unui candidat devin publice numai în măsura în care sunt destinate publicării. Comentariile aprobate afișează numele sau pseudonimul ales de autor. Numele și datele de contact din sesizări ori raportări de costuri nu sunt afișate public.'],
      ['Raportările de costuri', 'Pentru apă și salubritate colectăm separat localitatea, perioada, suma și, dacă sunt completate, consumul, numărul de persoane și numele. Numele este opțional, rămâne numai în baza de date și nu apare în statistici. Cu acord separat, păstrăm maximum 90 de zile numai tipul general al dispozitivului, sistemul de operare și browserul, fără identificatori hardware. Publicăm suma doar ca interval, iar statisticile sunt agregate.'],
      ['Securitate și prevenirea abuzurilor', 'Folosim sesiuni semnate, protecție CSRF, limitarea încercărilor de autentificare și identificatori pseudonimi pentru a împiedica voturile, reacțiile, comentariile ori sesizările repetate. Pentru raportările de costuri, adresa IP este transformată într-un cod criptografic nereversibil și permite maximum trei raportări pentru fiecare serviciu în 90 de zile; IP-ul nu este păstrat în clar. Pentru alte formulare, amprentele IP temporare sunt eliminate după aproximativ o zi.'],
      ['Scopuri și temeiuri', 'Prelucrăm datele, după caz, pentru furnizarea serviciului și administrarea conturilor, pe baza contractului; pentru securitate, moderare, apărarea drepturilor și informarea comunității, pe baza interesului legitim; pentru respectarea obligațiilor legale; sau pe baza consimțământului, atunci când acesta este cerut expres. Consimțământul poate fi retras pentru viitor, fără a afecta prelucrarea deja efectuată legal.'],
      ['Furnizori și transferuri', 'Aplicația folosește furnizori tehnici pentru găzduire și stocare, autentificare, email tranzacțional și, numai când funcția este pornită intenționat, redactare asistată ori publicare pe rețele sociale. Aceștia pot include Netlify, Supabase, Resend, OpenAI, Meta și TikTok. Unele servicii pot prelucra date în afara Spațiului Economic European, cu garanțiile contractuale aplicabile. Fonturile și imaginile încărcate de pe servicii externe pot transmite acelui serviciu adresa IP și informații tehnice ale browserului.'],
      ['Cât timp păstrăm datele', 'După 90 de zile ștergem raportarea individuală, inclusiv numele, observațiile, codul criptografic al IP-ului, dispozitivul și momentul exact al trimiterii. Păstrăm permanent numai statistica anonimă: serviciul, localitatea, perioada, intervalul sumei, numărul de raportări și totalurile agregate. Pentru alte formulare, amprentele IP anti-abuz sunt eliminate după aproximativ o zi, iar linkurile de resetare a parolei expiră după o oră. Celelalte date sunt păstrate numai cât este necesar pentru scopurile și obligațiile descrise.'],
      ['Drepturile tale', 'În condițiile Regulamentului (UE) 2016/679, poți cere accesul, rectificarea, ștergerea, restricționarea sau portabilitatea datelor și te poți opune anumitor prelucrări. Poți depune și o plângere la Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP). O solicitare poate necesita verificarea identității, iar unele drepturi pot avea limite legale, inclusiv în context editorial.'],
      ['Contact', 'Pentru întrebări sau cereri privind datele personale folosește adresa juridică afișată mai jos. Precizează suficient de clar operațiunea vizată, fără a trimite prin email parole sau alte secrete de autentificare.'],
    ],
  },
  cookies: {
    title: 'Politica de cookies',
    updated: '10 septembrie 2026',
    intro: 'Folosim tehnologii strict necesare pentru autentificare, securitate și funcționarea formularelor. Reținem și alegerea de a închide informarea despre cookies. În prezent nu folosim cookie-uri de publicitate sau analiză a comportamentului.',
    cookies: [
      ['sesiune', 'Menține sesiunea de autentificare și informațiile tehnice necesare formularelor, sondajelor și reacțiilor; este protejat împotriva accesului din JavaScript.', 'Cel mult 8 ore', 'Strict necesar'],
      ['sesiune.sig', 'Verifică integritatea cookie-ului de sesiune și împiedică modificarea lui neautorizată.', 'Cel mult 8 ore', 'Strict necesar'],
      ['vocea-cookie-notice-v1 (localStorage)', 'Reține pe acest browser închiderea informării despre cookies. Conține numai momentul expirării, fără identificator de vizitator; nu este transmis serverului.', '180 de zile; valoarea expirată este eliminată la următoarea vizită pe pagina principală', 'Preferință pentru afișarea informării'],
    ],
    sections: [
      ['Ce este un cookie', 'Un cookie este un fișier text de dimensiuni mici salvat de browser pentru ca un site să recunoască o sesiune și să păstreze în siguranță starea necesară între cereri.'],
      ['Informarea de pe pagina principală', 'La prima vizită afișăm un mesaj cu linkuri către această politică și politica de confidențialitate. Butonul „Am înțeles” închide mesajul și reține această alegere timp de 180 de zile în browser. Îl poți redeschide oricând prin „Informații despre cookies” din subsolul paginii principale. Dacă stocarea este blocată sau ștearsă, mesajul poate reapărea.'],
      ['Cookie-uri strict necesare', 'Cookie-urile de sesiune sunt necesare pentru serviciul cerut și securitatea lui. Nu sunt folosite pentru reclamă sau profilare și nu cer consimțământ separat. Butonul „Am înțeles” confirmă citirea informării; nu reprezintă acord pentru cookie-uri opționale și nu acceptă Termenii de utilizare.'],
      ['Stocare temporară în browser', 'Editorul asistat folosește sessionStorage, care nu este cookie, pentru a păstra temporar starea unei sarcini de redactare în browserul utilizatorului autentificat. În mod normal, informația rămâne până la închiderea sesiunii filei de browser.'],
      ['Controlul din browser', 'Poți șterge sau bloca aceste date din setările browserului, dar autentificarea, protecția formularelor, sondajele ori reacțiile pot înceta să funcționeze corect. Ștergerea cookie-urilor închide, de regulă, sesiunea activă.'],
      ['Servicii și pagini externe', 'Linkurile, fonturile sau imaginile furnizate de servicii externe pot fi supuse propriilor politici și pot folosi tehnologii asupra cărora această platformă nu are control. Verifică politica serviciului respectiv înainte de a-l utiliza.'],
      ['Modificări viitoare', 'Dacă vom introduce cookie-uri opționale de analiză, publicitate sau profilare, vom actualiza această politică și vom solicita alegerea utilizatorului înainte ca ele să fie activate.'],
    ],
  },
  raportare: {
    title: 'Raportarea conținutului',
    intro: 'Orice persoană poate semnala gratuit un material posibil ilegal sau contrar regulilor platformei.',
    sections: [
      ['Cum raportezi', 'Deschide articolul și folosește butonul „Raportează materialul”. Indică motivul, explică suficient de clar problema și, când este posibil, arată ce afirmație sau imagine este vizată.'],
      ['Ce se întâmplă', 'Sesizarea primește un identificator intern și este analizată de Super Admin. Materialul poate fi suspendat pe durata verificării, restabilit, respins sau închis cu o motivare păstrată în jurnal.'],
      ['Autorități și urgențe', 'Pentru pericole imediate contactează serviciile de urgență sau autoritatea competentă. Formularul platformei nu înlocuiește o plângere oficială și nu oferă consultanță juridică.'],
    ],
  },
};
