[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  included_files = ["views/**", "public/**"]

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/candidate-assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
